# Generated by Django 5.0.7 on 2024-08-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='snail.jpg', upload_to=''),
        ),
    ]
